package loot.generator;

import java.util.HashMap;
import javax.swing.JTable;
import javax.swing.UIManager;

/**
 *
 * @author bcmchs
 */
public class LootTableGUI extends javax.swing.JDialog {

    private MagicItemsGUI magicItems;

    /**
     * Creates new form LootTableGUI
     */
    public LootTableGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        magicItems = new MagicItemsGUI();
        mainTabbedPane.add(magicItems, "Magic Items");
        resizeTables();
    }

    private void resizeTables() {
    }

    public HashMap<String, JTable> getTables() {
        HashMap<String, JTable> hashMap = new HashMap<>();
        hashMap.put(level1Table.getName(), level1Table);
        hashMap.put(level2Table.getName(), level2Table);
        hashMap.put(level3Table.getName(), level3Table);
        hashMap.put(level4Table.getName(), level4Table);
        hashMap.put(level5Table.getName(), level5Table);
        hashMap.put(level6Table.getName(), level6Table);
        hashMap.put(level7Table.getName(), level7Table);
        hashMap.put(level8Table.getName(), level8Table);
        hashMap.put(level9Table.getName(), level9Table);
        hashMap.put(level10Table.getName(), level10Table);
        hashMap.put(level11Table.getName(), level11Table);
        hashMap.put(level12Table.getName(), level12Table);
        hashMap.put(level13Table.getName(), level13Table);
        hashMap.put(level14Table.getName(), level14Table);
        hashMap.put(level15Table.getName(), level15Table);
        hashMap.put(level16Table.getName(), level16Table);
        hashMap.put(level17Table.getName(), level17Table);
        hashMap.put(level18Table.getName(), level18Table);
        hashMap.put(level19Table.getName(), level19Table);
        hashMap.put(level20Table.getName(), level20Table);

        hashMap.put(gemsTable.getName(), gemsTable);
        hashMap.put(artTable.getName(), artTable);
        hashMap.put(mundaneTypesTable.getName(), mundaneTypesTable);
        hashMap.put(armorSizeTable.getName(), armorSizeTable);
        hashMap.put(mundaneArmorTypeTable.getName(), mundaneArmorTypeTable);
        hashMap.put(mundaneWeaponsTable.getName(), mundaneWeaponsTable);
        hashMap.put(toolsAndGearTable.getName(), toolsAndGearTable);
        hashMap.put(alchemicalItemsTable.getName(), alchemicalItemsTable);
        hashMap.put(darkwoodTable.getName(), darkwoodTable);
        hashMap.put(masterworkShieldTable.getName(), masterworkShieldTable);

        hashMap.put(weaponTypeDeterminationTable.getName(), weaponTypeDeterminationTable);
        hashMap.put(commonMeleeWeaponsTable.getName(), commonMeleeWeaponsTable);
        hashMap.put(uncommonWeaponsTable.getName(), uncommonWeaponsTable);
        hashMap.put(commonRangedWeaponsTable.getName(), commonRangedWeaponsTable);
        hashMap.put(ammunitionTable.getName(), ammunitionTable);

        //Add all tables from Magic Items GUI
        HashMap<String, JTable> tables = magicItems.getTables();
        for (String s : tables.keySet()) {
            JTable table = tables.get(s);
            hashMap.put(s, table);
        }
        return hashMap;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeTablesButton = new javax.swing.JButton();
        mainTabbedPane = new javax.swing.JTabbedPane();
        levelTabbedPane = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        level1Table = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        level2Table = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        level3Table = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        level4Table = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        level5Table = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        level6Table = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        level7Table = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        level8Table = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        level9Table = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane26 = new javax.swing.JScrollPane();
        level10Table = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane27 = new javax.swing.JScrollPane();
        level11Table = new javax.swing.JTable();
        jPanel22 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane29 = new javax.swing.JScrollPane();
        level12Table = new javax.swing.JTable();
        jPanel24 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane31 = new javax.swing.JScrollPane();
        level13Table = new javax.swing.JTable();
        jPanel25 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane32 = new javax.swing.JScrollPane();
        level14Table = new javax.swing.JTable();
        jPanel26 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane33 = new javax.swing.JScrollPane();
        level15Table = new javax.swing.JTable();
        jPanel21 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane28 = new javax.swing.JScrollPane();
        level16Table = new javax.swing.JTable();
        jPanel27 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane34 = new javax.swing.JScrollPane();
        level17Table = new javax.swing.JTable();
        jPanel28 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane35 = new javax.swing.JScrollPane();
        level18Table = new javax.swing.JTable();
        jPanel29 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane36 = new javax.swing.JScrollPane();
        level19Table = new javax.swing.JTable();
        jPanel30 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane37 = new javax.swing.JScrollPane();
        level20Table = new javax.swing.JTable();
        mundaneItemsTabbedPane = new javax.swing.JTabbedPane();
        mundaneTypesPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mundaneTypesTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        alchemicalItemsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        alchemicalItemsTable = new javax.swing.JTable();
        armorSizePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        armorSizeTable = new javax.swing.JTable();
        armorTypeTabbedPane = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        mundaneArmorTypeTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        darkWoodPanel = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        darkwoodTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        masterWorkShieldPanel = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        masterworkShieldTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        weaponPanel = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        mundaneWeaponsTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        toolsAndGearPanel = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        toolsAndGearTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        gemsPanel = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        gemsTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        artTable = new javax.swing.JTable();
        weaponTypesPanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane20 = new javax.swing.JScrollPane();
        weaponTypeDeterminationTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        commonMeleeWeaponsTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        uncommonWeaponsTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane23 = new javax.swing.JScrollPane();
        commonRangedWeaponsTable = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane24 = new javax.swing.JScrollPane();
        ammunitionTable = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);

        closeTablesButton.setText("Close Tables");
        closeTablesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeTablesButtonActionPerformed(evt);
            }
        });

        mainTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel10.setText("\"Level 1\"");

        level1Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-14  ", " ", "01-90  ", " ", "01-71  ", " "},
                {"15-29  ", "1d6 x 1,000 cp  ", "91-95  ", "1 gem  ", "72-95  ", "1 mundane  "},
                {"30-52  ", "1d8 x 100 sp  ", "96-100  ", "1 art  ", "96-100  ", "1 minor  "},
                {"53-95  ", "2d8 x 10 gp  ", " ", " ", " ", " "},
                {"96-100  ", "1d4 x 10 pp  ", " ", " ", " ", " "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level1Table.setName("Level 1"); // NOI18N
        jScrollPane2.setViewportView(level1Table);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 1", jPanel9);

        jLabel11.setText("\"Level 2\"");

        level2Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-13  ", " ", "01-81  ", " ", "01-49  ", " "},
                {"14-23  ", "1d10 x 1,000 cp  ", "82-95  ", "1d3 gems  ", "50-85  ", "1 mundane  "},
                {"24-43  ", "2d10 x 100 sp  ", "96-100  ", "1d3 art  ", "86-100  ", "1 minor  "},
                {"44-95  ", "4d10 x 10 gp  ", " ", " ", " ", " "},
                {"96-100  ", "2d8 x 10 pp  ", " ", " ", " ", " "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level2Table.setName("Level 2"); // NOI18N
        jScrollPane7.setViewportView(level2Table);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 2", jPanel10);

        jLabel12.setText("\"Level 3\"");

        level3Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-11  ", " ", "01-77  ", " ", "01-49  ", " "},
                {"12-21  ", "2d10 x 1,000 cp  ", "78-95  ", "1d3 gems  ", "50-79  ", "1d3 mundane  "},
                {"22-41  ", "4d8 x 100 sp  ", "96-100  ", "1d3 art  ", "80-100  ", "1 minor  "},
                {"42-95  ", "1d4 x 100 gp  ", " ", " ", " ", " "},
                {"96-100  ", "1d10 x 10 pp  ", " ", " ", " ", " "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level3Table.setName("Level 3"); // NOI18N
        jScrollPane8.setViewportView(level3Table);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 3", jPanel11);

        jLabel13.setText("\"Level 4\"");

        level4Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-11  ", " ", "01-70  ", " ", "01-42  ", " "},
                {"12-21  ", "3d10 x 1,000 cp  ", "71-95  ", "1d4 gems  ", "43-62  ", "1d4 mundane  "},
                {"22-41  ", "4d12 x 1,000 sp  ", "96-100  ", "1d3 art  ", "63-100  ", "1 minor  "},
                {"42-95  ", "1d6 x 100 gp  ", " ", " ", " ", " "},
                {"96-100  ", "1d8 x 10 pp  ", " ", " ", " ", " "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level4Table.setName("Level 4"); // NOI18N
        jScrollPane9.setViewportView(level4Table);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 4", jPanel13);

        jLabel14.setText("\"Level 5\"");

        level5Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-10  ", " ", "01-60  ", " ", "01-57  ", " "},
                {"11-19  ", "1d4 x 10,000 cp  ", "61-95  ", "1d4 gems  ", "58-67  ", "1d4 mundane  "},
                {"20-38  ", "1d6 x 1,000 sp  ", "96-100  ", "1d4 art  ", "68-100  ", "1d3 minor  "},
                {"39-95  ", "1d8 x 100 gp  ", " ", " ", " ", " "},
                {"96-100  ", "1d10 x 10 pp  ", " ", " ", " ", " "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level5Table.setName("Level 5"); // NOI18N
        jScrollPane10.setViewportView(level5Table);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 5", jPanel14);

        jLabel15.setText("\"Level 6\"");

        level6Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-10  ", " ", "01-56  ", " ", "01-54  ", " "},
                {"11-18  ", "1d6 x 10,000 cp  ", "57-92  ", "1d4 gems  ", "55-59  ", "1d4 mundane  "},
                {"19-37  ", "1d8 x 1,000 sp  ", "93-100  ", "1d4 art  ", "60-99  ", "1d3 minor  "},
                {"38-95  ", "1d10 x 100 gp  ", "", " ", "100", "1 medium  "},
                {"96-100  ", "1d12 x 10 pp  ", " ", " ", " ", " "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level6Table.setName("Level 6"); // NOI18N
        jScrollPane11.setViewportView(level6Table);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 6", jPanel15);

        jLabel20.setText("\"Level 7\"");

        level7Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-11  ", " ", "01-48  ", " ", "01-51  ", " "},
                {"12-18  ", "1d10 x 10,000 cp  ", "49-88  ", "1d4 gems  ", "52-97  ", "1d3 minor  "},
                {"19-35  ", "1d12 x 1,000 sp  ", "89-100  ", "1d4 art  ", "98-100  ", "1 medium  "},
                {"36-93  ", "2d6 x 100 gp  ", " ", " ", " ", " "},
                {"94-100  ", "3d4 x 10 pp  ", " ", " ", " ", " "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level7Table.setName("Level 7"); // NOI18N
        jScrollPane12.setViewportView(level7Table);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 7", jPanel16);

        jLabel23.setText("\"Level 8\"");

        level8Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-10  ", " ", "01-45  ", " ", "01-48  ", " "},
                {"11-15  ", "1d12 x 10,000 cp  ", "46-85  ", "1d6 gems  ", "49-96  ", "1d4 minor  "},
                {"16-29  ", "2d6 x 1,000 sp  ", "86-100  ", "1d4 art  ", "97-100  ", "1 medium  "},
                {"30-87  ", "2d8 x 100 gp  ", " ", " ", " ", " "},
                {"88-100  ", "3d6 x 10 pp  ", " ", " ", " ", " "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level8Table.setName("Level 8"); // NOI18N
        jScrollPane18.setViewportView(level8Table);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 8", jPanel17);

        jLabel24.setText("\"Level 9\"");

        level9Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-10  ", " ", "01-40  ", " ", "01-43  ", " "},
                {"11-15  ", "2d6 x 10,000 cp  ", "41-80  ", "1d8 gems  ", "44-91  ", "1d4 minor  "},
                {"16-29  ", "2d8 x 1,000 sp  ", "81-100  ", "1d4 art  ", "92-100  ", "1 medium  "},
                {"30-85  ", "5d4 x 100 gp  ", " ", " ", " ", " "},
                {"86-100  ", "2d12 x 10 pp  ", " ", " ", " ", " "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level9Table.setName("Level 9"); // NOI18N
        jScrollPane25.setViewportView(level9Table);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 9", jPanel18);

        jLabel25.setText("\"Level 10\"");

        level10Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-10  ", " ", "01-35  ", " ", "01-40  ", " "},
                {"11-24  ", "2d10 x 1,000 sp  ", "36-79  ", "1d8 gems  ", "41-88  ", "1d4 minor  "},
                {"25-79  ", "6d4 x 100 gp  ", "80-100  ", "1d6 art  ", "89-99  ", "1 medium  "},
                {"80-100  ", "5d6 x 10 pp  ", "100 ", " ", "100", "1 major  "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level10Table.setName("Level 10"); // NOI18N
        jScrollPane26.setViewportView(level10Table);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane26, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane26, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 10", jPanel19);

        jLabel26.setText("\"Level 11\"");

        level11Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-08  ", " ", "01-24  ", " ", "01-31  ", " "},
                {"09-14  ", "3d10 x 1,000 sp  ", "25-74  ", "1d10 gems  ", "32-84  ", "1d4 minor  "},
                {"15-75  ", "4d8 x 100 gp  ", "75-100  ", "1d6 art  ", "85-98  ", "1 medium  "},
                {"76-100  ", "4d10 x 10 pp  ", "", " ", "99-100  ", "1 major  "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level11Table.setName("Level 11"); // NOI18N
        jScrollPane27.setViewportView(level11Table);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane27, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane27, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 11", jPanel20);

        jLabel28.setText("\"Level 12\"");

        level12Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-08  ", " ", "01-17  ", " ", "01-27  ", " "},
                {"09-14  ", "3d12 x 1,000 sp  ", "18-70  ", "1d10 gems  ", "28-82  ", "1d6 minor  "},
                {"15-75  ", "1d4 x 1,000 gp  ", "71-100  ", "1d8 art  ", "83-97  ", "1 medium  "},
                {"76-100  ", "1d4 x 100 pp  ", "", " ", "98-100", "1 major  "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level12Table.setName("Level 12"); // NOI18N
        jScrollPane29.setViewportView(level12Table);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane29, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane29, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 12", jPanel22);

        jLabel30.setText("\"Level 13\"");

        level13Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-08  ", " ", "01-11  ", " ", "01-19  ", " "},
                {"09-75  ", "1d4 x 1,000 gp  ", "12-66  ", "1d12 gems  ", "20-73  ", "1d6 minor  "},
                {"76-100  ", "1d10 x 100 pp  ", "67-100  ", "1d10 art  ", "74-95  ", "1 medium  "},
                {"", " ", " ", " ", "96-100  ", "1 major  "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level13Table.setName("Level 13"); // NOI18N
        jScrollPane31.setViewportView(level13Table);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane31, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane31, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 13", jPanel24);

        jLabel31.setText("\"Level 14\"");

        level14Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-08  ", " ", "01-11  ", " ", "01-19  ", " "},
                {"09-75  ", "1d6 x 1,000 gp  ", "12-66  ", "2d8 gems  ", "20-58  ", "1d6 minor  "},
                {"76-100  ", "1d12 x 100 pp  ", "67-100  ", "2d6 art  ", "59-92  ", "1 medium  "},
                {"", " ", " ", " ", "93-100  ", "1 major  "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level14Table.setName("Level 14"); // NOI18N
        jScrollPane32.setViewportView(level14Table);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane32, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane32, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 14", jPanel25);

        jLabel32.setText("\"Level 15\"");

        level15Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-03  ", " ", "01-09  ", " ", "01-11  ", " "},
                {"04-74  ", "1d8 x 1,000 gp  ", "10-65  ", "2d10 gems  ", "12-46  ", "1d10 minor  "},
                {"75-100  ", "3d4 x 100 pp  ", "66-100  ", "2d8 art  ", "47-90  ", "1 medium  "},
                {"", " ", " ", " ", "91-100  ", "1 major  "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level15Table.setName("Level 15"); // NOI18N
        jScrollPane33.setViewportView(level15Table);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane33, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane33, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 15", jPanel26);

        jLabel27.setText("\"Level 16\"");

        level16Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-03  ", " ", "01-07  ", " ", "01-40  ", " "},
                {"04-74  ", "1d12 x 1,000 gp  ", "08-64  ", "4d6 gems  ", "41-46  ", "1d10 minor  "},
                {"75-100  ", "3d4 x 100 pp  ", "65-100  ", "2d10 art  ", "47-90  ", "1d3 medium  "},
                {"", " ", " ", " ", "91-100  ", "1 major  "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level16Table.setName("Level 16"); // NOI18N
        jScrollPane28.setViewportView(level16Table);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane28, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane28, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 16", jPanel21);

        jLabel33.setText("\"Level 17\"");

        level17Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-03  ", " ", "01-04  ", " ", "01-33  ", " "},
                {"04-68  ", "3d4 x 1,000 gp  ", "05-63  ", "4d8 gems  ", "34-83  ", "1d3 medium  "},
                {"69-100  ", "2d10 x 100 pp  ", "64-100  ", "3d8 art  ", "84-100  ", "1 major  "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level17Table.setName("Level 17"); // NOI18N
        jScrollPane34.setViewportView(level17Table);

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane34, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane34, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 17", jPanel27);

        jLabel34.setText("\"Level 18\"");

        level18Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-02  ", " ", "01-04  ", " ", "01-24  ", " "},
                {"03-65  ", "3d6 x 1,000 gp  ", "05-54  ", "3d12 gems  ", "25-80  ", "1d4 medium  "},
                {"66-100  ", "5d4 x 100 pp  ", "55-100  ", "3d10 art  ", "81-100  ", "1 major  "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level18Table.setName("Level 18"); // NOI18N
        jScrollPane35.setViewportView(level18Table);

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane35, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane35, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 18", jPanel28);

        jLabel35.setText("\"Level 19\"");

        level19Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-02  ", " ", "01-03  ", " ", "01-04  ", " "},
                {"03-65  ", "3d8 x 1,000 gp  ", "04-50  ", "6d6 gems  ", "05-70  ", "1d4 medium  "},
                {"66-100  ", "3d10 x 100 pp  ", "51-100  ", "6d6 art  ", "71-100  ", "1 major  "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level19Table.setName("Level 19"); // NOI18N
        jScrollPane36.setViewportView(level19Table);

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane36, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane36, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 19", jPanel29);

        jLabel36.setText("\"Level 20\"");

        level20Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-02  ", " ", "01-02  ", " ", "01-25  ", " "},
                {"03-65  ", "4d8 x 1,000 gp  ", "03-38  ", "4d10 gems  ", "26-65  ", "1d4 medium  "},
                {"66-100  ", "4d10 x 100 pp  ", "39-100  ", "7d6 art  ", "66-100  ", "1d3 major  "}
            },
            new String [] {
                "Roll", "Coins", "Roll", "Goods", "Roll", "Items"
            }
        ));
        level20Table.setName("Level 20"); // NOI18N
        jScrollPane37.setViewportView(level20Table);

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane37, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane37, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        levelTabbedPane.addTab("Level 20", jPanel30);

        mainTabbedPane.addTab("Encounter Levels", levelTabbedPane);

        mundaneTypesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-17", "Alchemical item", "[Alchemical Items]"},
                {"18-50", "Armor", "[Armor Size] AND [Mundane Armor Type]"},
                {"51-83", "Weapons", "[Mundane Weapons]"},
                {"84-100", "Tools and gear", "[Tools and Gear]"}
            },
            new String [] {
                "Roll", "Type", "Next Table"
            }
        ));
        mundaneTypesTable.setName("Mundane Types"); // NOI18N
        jScrollPane3.setViewportView(mundaneTypesTable);

        jLabel2.setText("\"Mundane Types\"");

        javax.swing.GroupLayout mundaneTypesPanelLayout = new javax.swing.GroupLayout(mundaneTypesPanel);
        mundaneTypesPanel.setLayout(mundaneTypesPanelLayout);
        mundaneTypesPanelLayout.setHorizontalGroup(
            mundaneTypesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
            .addGroup(mundaneTypesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mundaneTypesPanelLayout.setVerticalGroup(
            mundaneTypesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mundaneTypesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mundaneItemsTabbedPane.addTab("Mundane Types", mundaneTypesPanel);

        jLabel3.setText("\"Alchemical Items\"");

        alchemicalItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-12", "Alchemist's fire (1d4 flasks, 20 gp each)"},
                {"13-24", "Acid (2d4 flasks, 10 gp each)"},
                {"25-36", "Smokesticks (1d4 sticks, 20 gp each)"},
                {"37-48", "Holy water (1d4 flasks, 25 gp each)"},
                {"49-62", "Antitoxin (1d4 doses, 50 gp each)"},
                {"63-74", "Everburning torch"},
                {"75-88", "Tanglefoot bags (1d4 bags, 50 gp each)"},
                {"89-100", "Thunderstones (1d4 stones, 30 gp each)"}
            },
            new String [] {
                "Roll", "Result"
            }
        ));
        alchemicalItemsTable.setName("Alchemical Items"); // NOI18N
        jScrollPane4.setViewportView(alchemicalItemsTable);

        javax.swing.GroupLayout alchemicalItemsPanelLayout = new javax.swing.GroupLayout(alchemicalItemsPanel);
        alchemicalItemsPanel.setLayout(alchemicalItemsPanelLayout);
        alchemicalItemsPanelLayout.setHorizontalGroup(
            alchemicalItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alchemicalItemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(622, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        alchemicalItemsPanelLayout.setVerticalGroup(
            alchemicalItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alchemicalItemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
        );

        mundaneItemsTabbedPane.addTab("Alchemical items", alchemicalItemsPanel);

        jLabel4.setText("\"Armor Size\"");

        armorSizeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-10", "Small"},
                {"11-100", "Medium"}
            },
            new String [] {
                "Roll", "Result"
            }
        ));
        armorSizeTable.setName("Armor Size"); // NOI18N
        jScrollPane5.setViewportView(armorSizeTable);

        javax.swing.GroupLayout armorSizePanelLayout = new javax.swing.GroupLayout(armorSizePanel);
        armorSizePanel.setLayout(armorSizePanelLayout);
        armorSizePanelLayout.setHorizontalGroup(
            armorSizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(armorSizePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        armorSizePanelLayout.setVerticalGroup(
            armorSizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(armorSizePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
        );

        mundaneItemsTabbedPane.addTab("Armor size", armorSizePanel);

        mundaneArmorTypeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-12", "Chain shirt", "100 gp", null},
                {"13-18", "Masterwork studded leather", "175 gp", null},
                {"19-26", "Breastplate", "200 gp", null},
                {"27-34", "Banded mail", "250 gp", null},
                {"35-54", "Half-plate", "600 gp", null},
                {"55-80", "Full plate", "1,500 gp", null},
                {"81-90", "Darkwood", null, "\"Darkwood\" AND [Darkwood]"},
                {"91-100", "Masterwork shield", null, "\"Masterwork\" AND [Masterwork Shield]"}
            },
            new String [] {
                "Roll", "Result", "Value", "Next table"
            }
        ));
        mundaneArmorTypeTable.setName("Mundane Armor Type"); // NOI18N
        jScrollPane6.setViewportView(mundaneArmorTypeTable);

        jLabel1.setText("\"Mundane Armor Type\"");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(593, Short.MAX_VALUE))
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
        );

        armorTypeTabbedPane.addTab("Type", jPanel12);

        darkwoodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-50", "Buckler", "205 gp"},
                {"51-100", "Shield", "257 gp"}
            },
            new String [] {
                "Roll", "Result", "Value"
            }
        ));
        darkwoodTable.setName("Darkwood"); // NOI18N
        jScrollPane16.setViewportView(darkwoodTable);

        jLabel5.setText("\"Darkwood\"");

        javax.swing.GroupLayout darkWoodPanelLayout = new javax.swing.GroupLayout(darkWoodPanel);
        darkWoodPanel.setLayout(darkWoodPanelLayout);
        darkWoodPanelLayout.setHorizontalGroup(
            darkWoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
            .addGroup(darkWoodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        darkWoodPanelLayout.setVerticalGroup(
            darkWoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, darkWoodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
        );

        armorTypeTabbedPane.addTab("Darkwood", darkWoodPanel);

        masterworkShieldTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-17", "Buckler", "165 gp"},
                {"18-40", "Light wooden shield", "153 gp"},
                {"41-60", "Light steel shield", "159 gp"},
                {"61-83", "Heavy wooden shield", "157 gp"},
                {"84-100", "Heavy steel shield", "170 gp"}
            },
            new String [] {
                "Roll", "Result", "Value"
            }
        ));
        masterworkShieldTable.setToolTipText("");
        masterworkShieldTable.setName("Masterwork Shield"); // NOI18N
        jScrollPane17.setViewportView(masterworkShieldTable);

        jLabel6.setText("\"Masterwork Shield\"");

        javax.swing.GroupLayout masterWorkShieldPanelLayout = new javax.swing.GroupLayout(masterWorkShieldPanel);
        masterWorkShieldPanel.setLayout(masterWorkShieldPanelLayout);
        masterWorkShieldPanelLayout.setHorizontalGroup(
            masterWorkShieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterWorkShieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );
        masterWorkShieldPanelLayout.setVerticalGroup(
            masterWorkShieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masterWorkShieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
        );

        armorTypeTabbedPane.addTab("Masterwork shield", masterWorkShieldPanel);

        mundaneItemsTabbedPane.addTab("Armor type", armorTypeTabbedPane);

        mundaneWeaponsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-50", "\"Masterwork\" AND [Common Melee Weapons]"},
                {"51-70", "\"Masterwork\" AND [Uncommon Weapons]"},
                {"71-100", "\"Masterwork\" AND [Common Ranged Weapons]"}
            },
            new String [] {
                "Roll", "Next Table"
            }
        ));
        mundaneWeaponsTable.setName("Mundane Weapons"); // NOI18N
        jScrollPane13.setViewportView(mundaneWeaponsTable);

        jLabel7.setText("\"Mundane Weapons\"");

        javax.swing.GroupLayout weaponPanelLayout = new javax.swing.GroupLayout(weaponPanel);
        weaponPanel.setLayout(weaponPanelLayout);
        weaponPanelLayout.setHorizontalGroup(
            weaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weaponPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(609, Short.MAX_VALUE))
            .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        weaponPanelLayout.setVerticalGroup(
            weaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, weaponPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
        );

        mundaneItemsTabbedPane.addTab("Weapons", weaponPanel);

        toolsAndGearTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-03", "Backpack, empty", "2 gp"},
                {"04-06", "Crowbar", "2 gp"},
                {"07-11", "Lantern, bullseye", "12 gp"},
                {"12-16", "Lock, simple", "20 gp"},
                {"17-21", "Lock, average", "40 gp"},
                {"22-28", "Lock, good", "80 gp"},
                {"29-35", "Lock, superior", "150 gp"},
                {"36-40", "Manacles, masterwork", "50 gp"},
                {"41-43", "Mirror, small steel", "10 gp"},
                {"44-46", "Rope, silk", "10 gp"},
                {"47-53", "Spyglass", "1,000 gp"},
                {"54-58", "Artisan's tools, masterwork", "55 gp"},
                {"59-63", "Climber's kit", "80 gp"},
                {"64-68", "Disguise kit", "50 gp"},
                {"69-73", "Healer's kit", "50 gp"},
                {"74-77", "Holy symbol, silver", "25 gp"},
                {"78-81", "Hourglass", "25 gp"},
                {"82-88", "Magnifying glass", "100 gp"},
                {"89-95", "Musical instrument, masterwork", "100 gp"},
                {"96-100", "Thieves' tools, masterwork", "50 gp"}
            },
            new String [] {
                "Roll", "Result", "Value"
            }
        ));
        toolsAndGearTable.setName("Tools and Gear"); // NOI18N
        jScrollPane14.setViewportView(toolsAndGearTable);

        jLabel8.setText("\"Tools and Gear\"");

        javax.swing.GroupLayout toolsAndGearPanelLayout = new javax.swing.GroupLayout(toolsAndGearPanel);
        toolsAndGearPanel.setLayout(toolsAndGearPanelLayout);
        toolsAndGearPanelLayout.setHorizontalGroup(
            toolsAndGearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolsAndGearPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        toolsAndGearPanelLayout.setVerticalGroup(
            toolsAndGearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolsAndGearPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
        );

        mundaneItemsTabbedPane.addTab("Tools and gear", toolsAndGearPanel);

        mainTabbedPane.addTab("Mundane Items", mundaneItemsTabbedPane);

        gemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-25", "4d4 gp", "10 gp", "Banded, eye, or moss agate; azurite; blue quartz; hematite; lapis lazuli; malachite; obsidian; rhodochrosite; tiger eye turquoise; freshwater (irregular) pearl"},
                {"26-50", "2d4x10 gp", "50 gp", "Bloodstone; carnelian; chalcedony; chrysoprase; citrine; iolite, jasper; moonstone; onyx; peridot; rock crystal (clear quartz); sard; sardonyx; rose, smoky, or star rose quartz; zircon"},
                {"51-70", "4d4x10 gp", "100 gp", "Amber; amethyst; chrysoberyl; coral; red or brown-green garnet; jade; jet; white, golden, pink, or silver pearl; red spinel, red-brown or deep green spinel; tourmaline"},
                {"71-90", "2d4x100 gp", "500 gp", "Alexandrite; aquamarine; violet garnet; black pearl; deep blue spinel; golden yellow topaz"},
                {"91-99", "4d4x100 gp", "1,000 gp", "Emerald; white, black, or fire opal; blue sapphire; fiery yellow or rich purple corundum; blue or black star sapphire; star ruby"},
                {"100", "2d4x1,000 gp", "5,000 gp", "Clearest bright green emerald; blue-white, canary, pink, brown, or blue diamond; jacinth"}
            },
            new String [] {
                "Roll", "Value", "Average", "Examples"
            }
        ));
        gemsTable.setName("Gems"); // NOI18N
        jScrollPane15.setViewportView(gemsTable);

        jLabel9.setText("\"Gems\"");

        javax.swing.GroupLayout gemsPanelLayout = new javax.swing.GroupLayout(gemsPanel);
        gemsPanel.setLayout(gemsPanelLayout);
        gemsPanelLayout.setHorizontalGroup(
            gemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(680, Short.MAX_VALUE))
            .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        gemsPanelLayout.setVerticalGroup(
            gemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Gems", gemsPanel);

        jLabel16.setText("\"Art\"");

        artTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-10", "1d10x10 gp", "55 gp", "Silver ewer; carved bone or ivory statuette; finely wrought small gold bracelet"},
                {"11-25", "3d6x10 gp", "105 gp", "Cloth of gold vestments; black velvet mask with numerous citrines; silver chalice with lapis lazuli gems"},
                {"26-40", "1d6x100 gp", "350 gp", "Large well-done wool tapestry; brass mug with jade inlays"},
                {"41-50", "1d10x100 gp", "550 gp", "Silver comb with moonstones; silver-plated steel longsword with jet jewel in hilt"},
                {"51-60", "2d6x100 gp", "700 gp", "Carved harp of exotic wood with ivory inlay and zircon gems; solid gold idol (10 lb.)"},
                {"61-70", "3d6x100 gp", "1,050 gp", "Gold dragon comb with red garnet eye; gold and topaz bottle stopper cork; ceremonial electrum dagger with a star ruby in the pommel"},
                {"71-80", "4d6x100 gp", "1,400 gp", "Eyepatch with mock eye of sapphire and moonstone; fire opal pendant on a fine gold chain; old masterpiece painting"},
                {"81-85", "5d6x100 gp", "1,750 gp", "Embroidered silk and velvet mantle with numerous moonstones; sapphire pendant on gold chain"},
                {"86-90", "1d4x1,000 gp", "2,500 gp", "Embroidered and bejeweled glove; jeweled anklet; gold music box"},
                {"91-95", "1d6x1,000 gp", "3,500 gp", "Golden circlet with four aquamarines; a string of small pink pearls (necklace)"},
                {"96-99", "2d4x1,000 gp", "5,000 gp", "Jeweled gold crown; jeweled electrum ring"},
                {"100", "2d6x1,000 gp", "7,000 gp", "Gold and ruby ring; gold cup set with emeralds"}
            },
            new String [] {
                "Roll", "Value", "Average", "Examples"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        artTable.setName("Art"); // NOI18N
        jScrollPane19.setViewportView(artTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabbedPane.addTab("Art", jPanel1);

        weaponTypeDeterminationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-70", "Common melee weapon", "[Common Melee Weapons]"},
                {"71-80", "Uncommon melee weapon", "[Uncommon Weapons]"},
                {"81-100", "Common ranged weapon", "[Common Ranged Weapons]"}
            },
            new String [] {
                "Roll", "Type", "Next Table"
            }
        ));
        weaponTypeDeterminationTable.setName("Weapon Type Determination"); // NOI18N
        jScrollPane20.setViewportView(weaponTypeDeterminationTable);

        jLabel17.setText("\"Weapon Type Determination\"");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Weapon type determination", jPanel3);

        jLabel18.setText("\"Common Melee Weapons\"");

        commonMeleeWeaponsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-04", "Dagger", "+302 gp"},
                {"05-14", "Greataxe", "+320 gp"},
                {"15-24", "Greatsword", "+350 gp"},
                {"25-28", "Kama", "+302 gp"},
                {"29-41", "Longsword", "+315 gp"},
                {"42-45", "Mace, light", "+305 gp"},
                {"46-50", "Mace, heavy", "+312 gp"},
                {"51-54", "Nunchaku", "+302 gp"},
                {"55-57", "Quarterstaff", "+600 gp"},
                {"58-61", "Rapier", "+320 gp"},
                {"62-66", "Scimitar", "+315 gp"},
                {"67-70", "Shortspear", "+302 gp"},
                {"71-74", "Siangham", "+303 gp"},
                {"75-84", "Sword, bastard", "+335 gp"},
                {"85-89", "Sword, short", "+310 gp"},
                {"90-100", "Waraxe, dwarven", "+330 gp"}
            },
            new String [] {
                "Roll", "Result", "Weapon cost"
            }
        ));
        commonMeleeWeaponsTable.setName("Common Melee Weapons"); // NOI18N
        jScrollPane21.setViewportView(commonMeleeWeaponsTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Common Melee Weapons", jPanel4);

        jLabel19.setText("\"Uncommon Weapons\"");

        uncommonWeaponsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-03", "Axe, orc double", "+660 gp"},
                {"04-07", "Battleaxe", "+310 gp"},
                {"08-10", "Chain, spiked", "+325 gp"},
                {"11-12", "Club", "+300 gp"},
                {"13-16", "Crossbow, hand", "+400 gp"},
                {"17-19", "Crossbow, repeating", "+550 gp"},
                {"20-21", "Dagger, punching", "+302 gp"},
                {"22-23", "Falchion", "+375 gp"},
                {"24-26", "Flail, dire", "+690 gp"},
                {"27-31", "Flail, heavy", "+315 gp"},
                {"32-35", "Flail, light", "+308 gp"},
                {"36-37", "Gauntlet", "+302 gp"},
                {"38-39", "Gauntlet, spiked", "+305 gp"},
                {"40-41", "Glaive", "+308 gp"},
                {"42-43", "Greatclub", "+305 gp"},
                {"44-45", "Guisarme", "+309 gp"},
                {"46-48", "Halberd", "+310 gp"},
                {"49-51", "Halfspear", "+301 gp"},
                {"52-54", "Hammer, gnome hooked", "+620 gp"},
                {"55-56", "Hammer, light", "+301 gp"},
                {"57-58", "Handaxe", "+306 gp"},
                {"59-61", "Kukri", "+308 gp"},
                {"62-64", "Lance", "+310 gp"},
                {"65-67", "Longspear", "+305 gp"},
                {"68-70", "Morningstar", "+308 gp"},
                {"71-72", "Net", "+320 gp"},
                {"73-74", "Pick, heavy", "+308 gp"},
                {"75-76", "Pick, light", "+304 gp"},
                {"77-78", "Ranseur", "+310 gp"},
                {"79-80", "Sap", "+301 gp"},
                {"81-82", "Scythe", "+318 gp"},
                {"83-84", "Shuriken", "+301 gp"},
                {"85-86", "Sickle", "+306 gp"},
                {"87-89", "Sword, two-bladed", "+700 gp"},
                {"90-91", "Trident", "+315 gp"},
                {"92-94", "Urgrosh, dwarven", "+650 gp"},
                {"95-97", "Warhammer", "+312 gp"},
                {"98-100", "Whip", "+301 gp"}
            },
            new String [] {
                "Roll", "Result", "Weapon cost"
            }
        ));
        uncommonWeaponsTable.setName("Uncommon Weapons"); // NOI18N
        jScrollPane22.setViewportView(uncommonWeaponsTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane22, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane22, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Uncommon Weapons", jPanel5);

        commonRangedWeaponsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-10", "Ammunition", null, "[Ammunition]"},
                {"11-15", "Axe, throwing", "+308 gp", null},
                {"16-25", "Crossbow, heavy", "+350 gp", null},
                {"26-35", "Crossbow, light", "+335 gp", null},
                {"36-39", "Dart", "+330 gp 5 sp", null},
                {"40-41", "Javelin", "+301 gp", null},
                {"42-46", "Shortbow", "+330 gp", null},
                {"47-51", "Shortbow, composite (+0 str bonus)", "+375 gp", null},
                {"52-56", "Shortbow, composite (+1 str bonus)", "+450 gp", null},
                {"57-61", "Shortbow, composite (+2 str bonus)", "+525 gp", null},
                {"62-65", "Sling", "+300 gp", null},
                {"66-75", "Longbow", "+375 gp", null},
                {"76-80", "Longbow, composite", "+400 gp", null},
                {"81-85", "Longbow, composite (+1 Str bonus)", "+500 gp", null},
                {"86-90", "Longbow, composite (+2 Str bonus)", "+600 gp", null},
                {"91-95", "Longbow, composite (+3 Str bonus)", "+700 gp", null},
                {"96-100", "Longbow, composite (+4 Str bonus)", "+800 gp", null}
            },
            new String [] {
                "Roll", "Result", "Weapon cost", "Next Table"
            }
        ));
        commonRangedWeaponsTable.setName("Common Ranged Weapons"); // NOI18N
        jScrollPane23.setViewportView(commonRangedWeaponsTable);

        jLabel21.setText("\"Common Ranged Weapons\"");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Common Ranged Weapons", jPanel2);

        ammunitionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-50", "+350 gp", "\"Arrows (50)\" AND [Common Ranged Weapons]"},
                {"50-80", "+350 gp", "\"Bolts, crossbow (50)\" AND [Common Ranged Weapons]"},
                {"81-100", "+350 gp", "\"Bullets, sling (50)\" AND [Common Ranged Weapons]"}
            },
            new String [] {
                "Roll", "Weapon cost", "Next Table"
            }
        ));
        ammunitionTable.setName("Ammunition"); // NOI18N
        jScrollPane24.setViewportView(ammunitionTable);

        jLabel22.setText("\"Ammunition\"");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane24, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Ammunition", jPanel7);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Ranged", jPanel6);

        javax.swing.GroupLayout weaponTypesPanelLayout = new javax.swing.GroupLayout(weaponTypesPanel);
        weaponTypesPanel.setLayout(weaponTypesPanelLayout);
        weaponTypesPanelLayout.setHorizontalGroup(
            weaponTypesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        weaponTypesPanelLayout.setVerticalGroup(
            weaponTypesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        mainTabbedPane.addTab("Weapon Types", weaponTypesPanel);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("There's a bit here, but it's worth reading if you want to use this loot generator to its full effect.\nFirst off, all tables are modifiable.  If you change the range of rolls for a particular item, its changes will be used the next time you roll loot.\n\nThis tool uses a special \"table crawler\" for many items (mundane, magical).  The only items not utilizing the crawler are coins, gems, and art.\n\nThe crawler starts at an appropriate table (either \"Mundane Types\" or \"Magical Item Generation\").  It will roll a d%, then go to the row and column to determine the result.  If it's a minor, medium, or major item it will roll in that column.  For determining the result column, the crawler looks for a \"Next Table\" column, and barring text in that cell, that looks for a \"Result\" column.\n\nThe \"Next Table\" column can contain commands for the crawler:\nThe keyword AND allows the crawler to process multiple commands.\nAn command enclosed in quotes \"\" is added to the name of the item.\nBraces [] with the name of another table inside allows the crawler to move to that column next and determine a result.\nBuilt-in commands are represented by the @ symbol, followed by the name of the command.\n\nBuilt-in commands are used to determine results that need to be determined from multiple tables, and rely on information from the previous table in order to determine the next table.\n\nAn example of a built-in command is @SCROLL, which does several things:\n- Determines whether the scroll is Arcane or Divine\n- Determines a level for the scroll\n- Uses the above information to ultimately determine the scroll type\n\nIn generally, you can change cell values to better suit your needs, or even use the \"Next Table\" column to change crawler paths around.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabbedPane.addTab("Notes", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(closeTablesButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(closeTablesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 539, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeTablesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeTablesButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeTablesButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alchemicalItemsPanel;
    private javax.swing.JTable alchemicalItemsTable;
    private javax.swing.JTable ammunitionTable;
    private javax.swing.JPanel armorSizePanel;
    private javax.swing.JTable armorSizeTable;
    private javax.swing.JTabbedPane armorTypeTabbedPane;
    private javax.swing.JTable artTable;
    private javax.swing.JButton closeTablesButton;
    private javax.swing.JTable commonMeleeWeaponsTable;
    private javax.swing.JTable commonRangedWeaponsTable;
    private javax.swing.JPanel darkWoodPanel;
    private javax.swing.JTable darkwoodTable;
    private javax.swing.JPanel gemsPanel;
    private javax.swing.JTable gemsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable level10Table;
    private javax.swing.JTable level11Table;
    private javax.swing.JTable level12Table;
    private javax.swing.JTable level13Table;
    private javax.swing.JTable level14Table;
    private javax.swing.JTable level15Table;
    private javax.swing.JTable level16Table;
    private javax.swing.JTable level17Table;
    private javax.swing.JTable level18Table;
    private javax.swing.JTable level19Table;
    private javax.swing.JTable level1Table;
    private javax.swing.JTable level20Table;
    private javax.swing.JTable level2Table;
    private javax.swing.JTable level3Table;
    private javax.swing.JTable level4Table;
    private javax.swing.JTable level5Table;
    private javax.swing.JTable level6Table;
    private javax.swing.JTable level7Table;
    private javax.swing.JTable level8Table;
    private javax.swing.JTable level9Table;
    private javax.swing.JTabbedPane levelTabbedPane;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel masterWorkShieldPanel;
    private javax.swing.JTable masterworkShieldTable;
    private javax.swing.JTable mundaneArmorTypeTable;
    private javax.swing.JTabbedPane mundaneItemsTabbedPane;
    private javax.swing.JPanel mundaneTypesPanel;
    private javax.swing.JTable mundaneTypesTable;
    private javax.swing.JTable mundaneWeaponsTable;
    private javax.swing.JPanel toolsAndGearPanel;
    private javax.swing.JTable toolsAndGearTable;
    private javax.swing.JTable uncommonWeaponsTable;
    private javax.swing.JPanel weaponPanel;
    private javax.swing.JTable weaponTypeDeterminationTable;
    private javax.swing.JPanel weaponTypesPanel;
    // End of variables declaration//GEN-END:variables
}
